# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Parth Paradkar
email: parthparadkar3@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Que sera, sera.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://thescriptninja.github.io" # the base hostname & protocol for your site
github_username:  thescriptninja
facebook_username: parth.paradkar.35
linkedin_username: parth-paradkar
twitter_username: thescriptninja_

# Build settings
markdown: kramdown
